name: Travis Heartbeat Dropbox

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Create log entry
        run: |
          echo "Heartbeat success at $(date)" > heartbeat.log

      - name: Upload to Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ secrets.DROPBOX_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\": \"/heartbeat.log\",\"mode\": \"append\",\"autorename\": false,\"mute\": false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @heartbeat.log
