name: Travis FTP Test

on:
  workflow_dispatch:

jobs:
  testftp:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "FTP test $(date -u)" > test.txt

      - name: FTP upload
        uses: sebastianpopp/ftp-action@v2
        with:
          host: ftp.drivehq.com
          user: ${{ secrets.DRIVEHQ_FTP_USER }}
          password: ${{ secrets.DRIVEHQ_FTP_PASSWORD }}
          localFiles: test.txt
          remoteDir: /drivehqshare
