name: Travis FTP Heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ftpbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write heartbeat
        run: echo "Travis heartbeat: $(date -u)" >> ftp_heartbeat.log

      - name: Upload via FTP
        uses: sebastianpopp/ftp-action@v2
        with:
          host: ftp.drivehq.com
          user: ${{ secrets.DRIVEHQ_FTP_USER }}
          password: ${{ secrets.DRIVEHQ_FTP_PASSWORD }}
          localDir: .
          remoteDir: /drivehqshare/travis
