name: gmail-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Gmail test
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
        run: |
          python <<'EOF'
          from google.oauth2.credentials import Credentials
          from googleapiclient.discovery import build

          creds = Credentials(
              None,
              refresh_token="${{ secrets.GMAIL_REFRESH_TOKEN }}",
              client_id="${{ secrets.GMAIL_CLIENT_ID }}",
              client_secret="${{ secrets.GMAIL_CLIENT_SECRET }}",
              token_uri="https://oauth2.googleapis.com/token"
          )

          service = build("gmail", "v1", credentials=creds)
          results = service.users().messages().list(userId="me", maxResults=5).execute()
          messages = results.get("messages", [])

          if not messages:
              print("✅ Connected to Gmail, but no messages found.")
          else:
              print("✅ Connected to Gmail. Showing up to 5 message IDs:")
              for msg in messages:
                  print(" -", msg["id"])
          EOF
