name: Google Drive Heartbeat

on:
  schedule:
    - cron: "*/2 * * * *"   # run every 2 minutes
  workflow_dispatch:

jobs:
  drive-heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Google Drive Heartbeat
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SVC_CREDENTIALS }}
        run: |
          python - <<'EOF'
          import os, json, time, io
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaIoBaseUpload

          # Load credentials from GitHub secret
          creds_json = os.environ["GOOGLE_CREDENTIALS"]
          creds_dict = json.loads(creds_json)
          creds = service_account.Credentials.from_service_account_info(
              creds_dict, scopes=["https://www.googleapis.com/auth/drive"]
          )

          service = build("drive", "v3", credentials=creds)

          # Heartbeat metadata
          timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
          filename = f"heartbeat-{timestamp}.txt"
          content = f"Heartbeat at {timestamp}"
          media = MediaIoBaseUpload(io.BytesIO(content.encode()), mimetype="text/plain")

          try:
              file = service.files().create(
                  body={"name": filename},
                  media_body=media,
                  fields="id"
              ).execute()

              print(f"✅ Heartbeat written to Google Drive: {filename} (id: {file['id']})")

              # Simulated NVRAM breadcrumbs
              breadcrumb = {
                  "source": "GoogleDrive",
                  "status": "success",
                  "timestamp": timestamp,
                  "file_id": file["id"]
              }
              print("Breadcrumb:", json.dumps(breadcrumb))

          except Exception as e:
              print(f"❌ Heartbeat failed: {e}")
              breadcrumb = {
                  "source": "GoogleDrive",
                  "status": "failure",
                  "timestamp": timestamp,
                  "error": str(e)
              }
              print("Breadcrumb:", json.dumps(breadcrumb))
              exit(1)
          EOF
