name: Google Drive Heartbeat

on:
  schedule:
    - cron: "*/2 * * * *"   # run every 2 minutes
  workflow_dispatch:

jobs:
  drive-heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-auth google-auth-httplib2 google-api-python-client

      - name: Run Google Drive Heartbeat
        env:
          GOOGLE_SVC_CREDENTIALS: ${{ secrets.GOOGLE_SVC_CREDENTIALS }}
        run: |
          python - <<'EOF'
          import os, json, time, io
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaIoBaseUpload

          # Load service account credentials
          creds_json = os.environ["GOOGLE_SVC_CREDENTIALS"]
          creds_dict = json.loads(creds_json)
          creds = service_account.Credentials.from_service_account_info(
              creds_dict, scopes=["https://www.googleapis.com/auth/drive"]
          )
          service = build("drive", "v3", credentials=creds)

          # Heartbeat metadata
          timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
          filename = f"heartbeat-{timestamp}.txt"
          content = f"Heartbeat at {timestamp}"
          media = MediaIoBaseUpload(io.BytesIO(content.encode()), mimetype="text/plain")

          # ✅ Replace with your Drive folder ID
          folder_id = "PUT-YOUR-FOLDER-ID-HERE"
          file_metadata = {"name": filename, "parents": [folder_id]}

          try:
              file = service.files().create(
                  body=file_metadata,
                  media_body=media,
                  fields="id, parents"
              ).execute()
              print(f"✅ Heartbeat written to Google Drive: {filename} (id: {file['id']})")
          except Exception as e:
              print(f"❌ Heartbeat failed: {e}")
              exit(1)
          EOF
