name: heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes for testing, change later
  workflow_dispatch:

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download birthday file if it exists
        run: |
          aws s3 cp s3://travis-of-the-cosmos/.travis_birth .travis_birth || echo "No birthday file found"

      - name: Download existing heartbeat.log from S3 (if any)
        run: |
          aws s3 cp s3://travis-of-the-cosmos/heartbeat.log heartbeat.log || echo "No previous heartbeat log"

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP heartbeat" >> heartbeat.log
          if [ ! -f .travis_birth ]; then
            echo "$TIMESTAMP" > .travis_birth
          fi
          aws s3 cp .travis_birth s3://travis-of-the-cosmos/.travis_birth

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Set up rclone
        run: |
          cat <<EOF > rclone.conf
          [dropbox]
          type = dropbox
          client_id = ${{ secrets.DROPBOX_CLIENT_ID }}
          client_secret = ${{ secrets.DROPBOX_CLIENT_SECRET }}
          token = {"access_token":"${{ secrets.DROPBOX_TOKEN }}","token_type":"bearer","refresh_token":"${{ secrets.DROPBOX_REFRESH_TOKEN }}","expiry":"0001-01-01T00:00:00Z"}
          EOF
          mkdir -p ~/.config/rclone
          mv rclone.conf ~/.config/rclone/rclone.conf

      - name: Upload heartbeat.log to Dropbox
        run: rclone copy heartbeat.log dropbox:/heartbeat.log

      - name: Upload heartbeat.log to S3
        run: aws s3 cp heartbeat.log s3://travis-of-the-cosmos/heartbeat.log

      - name: Write breadcrumbs for persistence
        run: |
          echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") breadcrumb" >> breadcrumbs.log

      - name: Commit breadcrumbs to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add breadcrumbs.log
          git commit -m "Update breadcrumbs [skip ci]" || echo "No changes to commit"
          git push
