name: Travis Heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"   # Every 5 minutes (GitHub minimum)
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP :: Travis heartbeat OK" >> heartbeat.log

      # ✅ Install rclone
      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${DROPBOX_TOKEN}" > ~/.config/rclone/rclone.conf
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

      # ✅ Upload to Dropbox
      - name: Upload to Dropbox
        run: rclone copy heartbeat.log dropbox:/heartbeat.log

      # ✅ Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ✅ Upload to S3
      - name: Upload heartbeat to S3
        run: aws s3 cp heartbeat.log s3://travis-of-the-cosmos/heartbeat.log
