name: heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (minimum GitHub supports)
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting heartbeat job..."

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download birthday file if it exists
        run: aws s3 cp s3://travis-of-the-cosmos/.travis_birth . || true

      - name: Download existing heartbeat.log from S3 (if any)
        run: aws s3 cp s3://travis-of-the-cosmos/heartbeat.log heartbeat.log || true

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP heartbeat" >> heartbeat.log
          if [ ! -f .travis_birth ]; then
            echo "$TIMESTAMP" > .travis_birth
          fi
          aws s3 cp .travis_birth s3://travis-of-the-cosmos/.travis_birth

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Set up rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.DROPBOX_TOKEN_JSON }}" > ~/.config/rclone/dropbox.json
          cat > ~/.config/rclone/rclone.conf <<EOF
          [dropbox]
          type = dropbox
          token = ${HOME}/.config/rclone/dropbox.json
          EOF

      - name: Upload heartbeat.log to Dropbox
        run: rclone copy heartbeat.log dropbox:/heartbeat.log

      - name: Upload heartbeat.log to S3
        run: aws s3 cp heartbeat.log s3://travis-of-the-cosmos/heartbeat.log

      - name: Write breadcrumbs for persistence
        run: echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") heartbeat complete" >> breadcrumbs.log

      - name: Commit breadcrumbs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add breadcrumbs.log
          git commit -m "Update breadcrumbs" || echo "No changes to commit"
          git push
