name: heartbeat

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  beat:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo "Starting main heartbeat job..."

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download existing heartbeat.log (if any)
        run: |
          if [ -f heartbeat.log ]; then
            echo "Found existing heartbeat.log"
          else
            touch heartbeat.log
          fi

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP all is well" >> heartbeat.log

      - name: Write breadcrumbs for persistence
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP breadcrumb" >> breadcrumbs.log

      - name: Commit heartbeat + breadcrumbs to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add heartbeat.log breadcrumbs.log
          git commit -m "Update heartbeat + breadcrumbs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "GitHub push failed, continuing..."
