name: heartbeat

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  beat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download birthday file if it exists
        run: aws s3 cp s3://travis-of-the-cosmos/.travis_birth .travis_birth || echo "No birthday file yet"

      - name: Download existing heartbeat.log from S3 (if any)
        run: aws s3 cp s3://travis-of-the-cosmos/heartbeat.log heartbeat.log || touch heartbeat.log

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP" >> heartbeat.log
          if [ ! -f .travis_birth ]; then
            echo "$TIMESTAMP" > .travis_birth
            aws s3 cp .travis_birth s3://travis-of-the-cosmos/.travis_birth
          fi

      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [dropbox]
          type = dropbox
          client_id = ${{ secrets.DROPBOX_CLIENT_ID }}
          client_secret = ${{ secrets.DROPBOX_CLIENT_SECRET }}
          token = ${{ secrets.DROPBOX_TOKEN_JSON }}
          EOF

      - name: Upload heartbeat.log to Dropbox
        run: rclone copy heartbeat.log dropbox:/heartbeat.log

      - name: Upload heartbeat.log to S3
        run: aws s3 cp heartbeat.log s3://travis-of-the-cosmos/heartbeat.log
