name: heartbeat

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (adjust if needed)
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download birthday file if it exists
        run: |
          aws s3 cp s3://travis-of-the-cosmos/.travis_birth .travis_birth || echo "No birth file yet"

      - name: Download existing heartbeat.log from S3 (if any)
        run: |
          aws s3 cp s3://travis-of-the-cosmos/heartbeat.log heartbeat.log || touch heartbeat.log

      - name: Generate heartbeat entry
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$TIMESTAMP heartbeat" >> heartbeat.log
          # Create/update heartbeat.json for the website
          echo "{\"timestamp\": \"$TIMESTAMP\"}" > heartbeat.json

      - name: Set up rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Upload heartbeat.log to Dropbox
        run: rclone copy heartbeat.log dropbox:/heartbeat.log

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload heartbeat.log to S3
        run: aws s3 cp heartbeat.log s3://travis-of-the-cosmos/heartbeat.log

      # ✅ NEW: Commit heartbeat.json into the repo so GitHub Pages can serve it
      - name: Commit heartbeat.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add heartbeat.json
          git commit -m "Update heartbeat.json [skip ci]" || echo "No changes to commit"
          git push
